travis:
  secure:
    BINSTAR_TOKEN: sew5joqWpF7FRpLdObx05PS6WeHgA+5XblYSbrQD1JArHsV+VQ6J4OwiWefRS0RiZyYqFpBOu2m9tEbChvF1K+NyqZaI0WtNeY/eoGIddhqKcfUTZZwFJ+TyfF/bVGTHKZN+XPaqRYr72yQ32RVxF2lsOgMovVNbWKcwKT24dJBLY6TRQ3gkBxo7+HyYO3IQpoR5fnYhC7FzW3/uJxiQUbwiynItu2pF9rbKpZCK76eH3o9wtmVaPJ6RmETlxO8LZRC+KnZCcLN9NLvcVnZAJtwmDvZGIT61SOB3kHuPX1gdT6mzgQq/rnfmM6jM4Jelug1G53Sojt16FB8A2QgBC6nnzy5wVbX/PAT8cNiK7Cp7nECYHwFAtppJRagdm4NqblHI4WSyLk7RhoaPqDbXVhANXUM1FZjCLZTHUlmX81NLOnbd8sLidrGr9uE/K2Xnr2FuOnRkUWxe/3gAnrCZtsxw/VGgoyJmVzFldOniJ/dcxbqfXipL/vNFujE1lIZ3lPFvPABwVs2HtETgytEHmWxlg4crHTi1TXbCI/ZzJ12ivRzoYnVLhg4/45NPgcrwhfjTNp3oqyFHelNjhXsXMQa5y2MuyNHSEEYnCBzj9m+eQXZcM1nqp4pvmd90HKb3HGnajRTjG6jKEoC07O8gv+Tum8o42u1cBp2byc0evjA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
